---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: products-app
description: Products Service Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: staging
---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/nagp-demo-382506/locations/asia-south2/clusters/staging