---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products-aps
spec:
  template:
    metadata:
      name: products-pod
      labels:
        app: products
        type: backend
        pod: products-pod
    spec:
      containers:
        -  name: products-container
           image: products
  replicas: 2
  selector:
    matchLabels:
      app: products
      type: backend
---
apiVersion: v1
kind: Service
metadata:
 name: app-loadbalancer-service
spec:
 type: ClusterIP
 ports:
 - targetPort: 8080
   port: 80
 selector:
  pod: products-pod